<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>IrisQuickQuery.App</RootNamespace>
    <AssemblyName>IrisQuickQuery</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\iris-app-icon.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.0.19</Version>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IrisQuickQuery.Core\IrisQuickQuery.Core.csproj" />
    <ProjectReference Include="..\IrisQuickQuery.Infrastructure\IrisQuickQuery.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IrisQuickQuery.Core.Tests" />
  </ItemGroup>
</Project>
